apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinitagain-sbs-ppc-social
  labels:
    app: spinitagain-sbs-ppc-social
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinitagain-sbs-ppc-social
  template:
    metadata:
      labels:
        app: spinitagain-sbs-ppc-social
    spec:
      containers:
        - name: spinitagain-sbs-ppc-social
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: spinitagain-sbs-ppc-social
  labels:
    app: spinitagain-sbs-ppc-social
spec:
  type: LoadBalancer
  selector:
    app: spinitagain-sbs-ppc-social
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  loadBalancerIP: LOAD_BALANCER_IP_PLACEHOLDER